### ISSUE TITLE
Should this be a snippet instead?

### ISSUE THREAD

**Issue by stabldev** [SxYxuse/svelte-5-kit-boilerplate#1]
https://github.com/SxYxuse/svelte-5-kit-boilerplate/blob/6a3b1d98dcf5b42828ea023df998240b231fd64a/src/routes/%2Blayout.svelte#L5

https://svelte-5-preview.vercel.app/docs/snippets#snippets-and-slots
still can be used but since this project is based on svelt5, wouldnt it be better to use snippet instead?
smth like:
```svelte
<script lang="ts">
    const { children } = $props();
</script>

{@render children()}
```

**Comment by SxYxuse** [comment]
Yeah sure, i did a mistake, thank's to you i've updated the boilerplate
